name: myhabits
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  duration: ^3.0.8
  flutter:
    sdk: flutter
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  path_provider: ^2.0.8
  toggle_switch: ^1.4.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
          weight: 900
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Light.ttf
          weight: 300

  assets:
    - images/
